site_name: PSHonolulu
repo_url: https://github.com/KevinMarquette/PSHonolulu
theme: readthedocs
pages:
- Home: index.md
- PSHonolulu Basics:
  - What is PSHonolulu: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
